name: FcloneByGdriveTalk

on:
  workflow_dispatch:

jobs: 
  build:
    name: Fclone Running
    runs-on: ubuntu-latest
    steps:
      - name: Preparing Source Code
        uses: actions/checkout@v2
      - name: Installing Required Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Installing Python3 and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Giving Permission
        run: chmod 777 fclone
      - name: Running the bot
        run: |
          python3 telegram_gcloner/telegram_gcloner.py
